version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: pump_sensor_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hackafuture
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: 
      context: ./app
      dockerfile: Backend_Dockerfile
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:hackafuture@db:5432/pump_sensor_data
    ports:
      - "8001:8001"

volumes:
  postgres_data: